from __future__ import annotations

from .models import AnalysisReport


def demo_reports() -> list[AnalysisReport]:
    base = dict(
        data_completeness_pct=92,
        data_as_of_et="2026-09-02 08:15 ET",
        discovered_by=["GAP_UP", "VOLUME_LEADER"],
        market_context={"regime": "RISK_ON"},
        sector_context={"name": "Technology", "etf": "XLK", "trend": "BULLISH"},
        technical={
            "weekly": {"trend": "BULLISH"},
            "daily": {"trend": "BULLISH"},
            "four_hour": {"trend": "BULLISH"},
        },
        relative_strength={"current_vs_spy": 8.2, "stock_vs_spy_5d": 6.1},
        news={
            "catalyst": "EARNINGS",
            "sentiment": "POSITIVE",
            "reaction": "POSITIVE_NEWS_ACCEPTED",
            "headlines": [],
        },
        livermore={
            "pivot_confirmed": False,
            "timeframes_aligned": 3,
            "book_principle": "Wait for price confirmation; do not buy merely because something looks cheap.",
            "add_rule": "Add only after favorable progress / a new confirmed pivot.",
        },
        scenarios={
            "meta": {"model": "HEURISTIC_NOT_CALIBRATED"},
            "bullish": {"probability_pct": 62},
            "neutral": {"probability_pct": 24},
            "bearish": {"probability_pct": 14},
        },
        missing=["Demo: fundamentals/macro intentionally omitted."],
    )
    return [
        AnalysisReport(
            ticker="GTLB",
            name="Demo Gap Corp",
            price=55.60,
            market_cap=7.62e9,
            gap_pct=23.31,
            direction="LONG",
            setup="GAP & GO LONG",
            state="WATCH",
            score=82.0,
            long_score=82.0,
            short_score=41.0,
            score_margin=41.0,
            score_breakdown={"market": 9, "sector": 8, "technical": 22, "volume": 10, "relative_strength": 9, "event_news": 10, "livermore": 14},
            pm_volume=103793,
            pm_volume_state="WATCH",
            runtime_rvol=4.1,
            runtime_rvol_session="PREMARKET",
            recent_5m_rvol=7.2,
            vwap=54.8,
            distance_from_vwap_pct=1.46,
            pm_high=56.2,
            pm_low=52.8,
            prior_pm_high=55.5,
            prior_pm_low=52.8,
            atr14=2.8,
            levels={
                "pivot": 55.5,
                "aggressive_trigger": 55.56,
                "conservative_trigger": 55.92,
                "stop_reference": 54.52,
                "invalidation": 54.8,
                "target_1r": 56.60,
                "target_2r": 57.64,
                "add_reference": 56.90,
                "do_not_trade_if": "Breakout fails or price loses invalidation.",
            },
            next_trigger="Wait for price confirmation above the pivot near $55.50 with volume participation.",
            why=["Gap Up +23.31% triggered discovery", "Recent 5m volume 7.2x normal", "Weekly/Daily/4H align"],
            risks=["PM volume is not yet QUALIFIED; this remains a watch/confirmation setup"],
            **base,
        ),
        AnalysisReport(
            ticker="DELL",
            name="Demo Large Cap",
            price=464.56,
            market_cap=274.6e9,
            gap_pct=9.29,
            direction="LONG",
            setup="GAP & GO LONG",
            state="ARMED",
            score=78.0,
            long_score=78.0,
            short_score=38.0,
            score_margin=40.0,
            score_breakdown={"market": 9, "sector": 8, "technical": 20, "volume": 9, "relative_strength": 8, "event_news": 10, "livermore": 14},
            pm_volume=174732,
            pm_volume_state="WATCH",
            runtime_rvol=3.0,
            runtime_rvol_session="PREMARKET",
            recent_5m_rvol=5.1,
            vwap=461.2,
            distance_from_vwap_pct=0.73,
            pm_high=465.0,
            pm_low=452.0,
            prior_pm_high=464.2,
            prior_pm_low=452.0,
            atr14=18.0,
            levels={
                "pivot": 464.2,
                "aggressive_trigger": 464.66,
                "conservative_trigger": 466.9,
                "stop_reference": 459.4,
                "invalidation": 461.2,
                "target_1r": 469.9,
                "target_2r": 475.2,
                "add_reference": 473.2,
                "do_not_trade_if": "Breakout fails or price loses invalidation.",
            },
            next_trigger="Watch for continued participation while price respects invalidation near $461.20.",
            why=["Gap Up +9.29% triggered discovery", "Earnings catalyst", "Large-cap institutional liquidity"],
            risks=["PM volume is still building"],
            **base,
        ),
    ]
